# --- Data logging ---
log_data: 1
log_path: "/home/admin/kilin_sbRIO_ws/kilin_fpga_driver/log/sample_test.csv"

MainLoop_period_us: 1000

# --- Calibration helper ---
Measure_offset: 0
Hall_calibration_vel: 0.2
Hall_calibration_tol: 0.005

# --- Scenario ---
Scenario: "Robot"   
# "SingleModule"

Enable: 1

L1:
  EN: 1
  Calibration_Bias: 0.0
  KP: 85
  KI: 0.3
  KD: 1.75
  KT: 2.0
  Torque_Feedforward: 0.0
  input_voltage: 300

L2:
  EN: 2
  FW_Version: 3
  Calibration_Bias: 0.0
  KP: 85
  KI: 0.3
  KD: 1.75
  KT: 2.0
  Torque_Feedforward: 0.0
  input_voltage: 300

L3:
  EN: 3
  FW_Version: 3
  Calibration_Bias: 0.0
  KP: 85
  KI: 0
  KD: 1.75
  KT: 2.0
  Torque_Feedforward: 0.0
  input_voltage: 300

R1:
  EN: 4
  FW_Version: 3
  Calibration_Bias: 0.0
  KP: 85
  KI: 0
  KD: 1.75
  KT: 2.0
  Torque_Feedforward: 0.0
  input_voltage: 300

R2:
  EN: 5
  FW_Version: 3
  Calibration_Bias: 0.0
  KP: 85
  KI: 0
  KD: 1.75
  KT: 2.0
  Torque_Feedforward: 0.0
  input_voltage: 300

R3:
  EN: 6
  FW_Version: 3
  Calibration_Bias: 0.0
  KP: 85
  KI: 0
  KD: 1.75
  KT: 2.0
  Torque_Feedforward: 0.0
  input_voltage: 300

Bus 1:
  L:
    id: 1
    Position: 1030
  R:  
    id: 2
    Position: 1000
Bus 2:
  L:
    id: 1
    Position: 1030
  R:
    id: 2
    Position: 1000
Bus 3:
  L:
    id: 1
    Position: 1030
  R:
    id: 2
    Position: 1000
  


Powerboard_Scaling_Factor:
  -  # 1
    Current_Factor: 1.0
    Current_Offset: 0.0
    Voltage_Factor: 1.0
    Voltage_Offset: 0.0
  -  # 2
    Current_Factor: 1.0
    Current_Offset: 0.0
    Voltage_Factor: 1.0
    Voltage_Offset: 0.0
  -  # L1
    Current_Factor: 1.0
    Current_Offset: 0.0
    Voltage_Factor: 1.0
    Voltage_Offset: 0.0
  -  # L2
    Current_Factor: 1.0
    Current_Offset: 0.0
    Voltage_Factor: 1.0
    Voltage_Offset: 0.0
  -  # L3
    Current_Factor: 1.0
    Current_Offset: 0.0
    Voltage_Factor: 1.0
    Voltage_Offset: 0.0
  -  # R1
    Current_Factor: 1.0
    Current_Offset: 0.0
    Voltage_Factor: 1.0
    Voltage_Offset: 0.0
  -  # R2
    Current_Factor: 1.0
    Current_Offset: 0.0
    Voltage_Factor: 1.0
    Voltage_Offset: 0.0
  -  # R3
    Current_Factor: 1.0
    Current_Offset: 0.0
    Voltage_Factor: 1.0
    Voltage_Offset: 0.0
  -  # Bus 
    Current_Factor: 1.0
    Current_Offset: 0.0
    Voltage_Factor: 1.0
    Voltage_Offset: 0.0
