# --- Data logging ---
log_data: 1
log_path: "/home/shuweiyang/kilin_sbRIO_ws/kilin_fpga_driver/log/sample_test.csv"

MainLoop_period_us: 1000
RS485_CMD_us: 200
RS485_IDLE_us: 50
RS485_READ_us: 150

Measure_offset: 0
Hall_calibration_vel: 0.2
Hall_calibration_tol: 0.005

# --- Scenario ---
Scenario: "Robot"   
# "SingleModule"

Motor:

  L1:
    Enable: 1
    KP: 85.0
    KI: 0.3
    KD: 1.75
    KT: 2.0
    Torque_Feedforward: 0.0
    input_voltage: 300

  L2:
    Enable: 1
    KP: 85.0
    KI: 0.3
    KD: 1.75
    KT: 2.0
    Torque_Feedforward: 0.0
    input_voltage: 300

  L3:
    Enable: 1
    KP: 85.0
    KI: 0.3
    KD: 1.75
    KT: 2.0
    Torque_Feedforward: 0.0
    input_voltage: 300

  R1:
    Enable: 1
    KP: 85.0
    KI: 0.3
    KD: 1.75
    KT: 2.0
    Torque_Feedforward: 0.0
    input_voltage: 300

  R2:
    Enable: 1
    KP: 85.0
    KI: 0.3
    KD: 1.75
    KT: 2.0
    Torque_Feedforward: 0.0
    input_voltage: 300

  R3:
    Enable: 1
    KP: 85.0
    KI: 0.3
    KD: 1.75
    KT: 2.0
    Torque_Feedforward: 0.0
    input_voltage: 300

Number_of_modules: 6
Modules_list:
  - L1
  - L2
  - L3
  - R1
  - R2
  - R3
#Servo:
#  Bus 1:
#    L:
#      id: 1
#      Position: 1030
#    R:  
#      id: 2
#      Position: 1000
#  Bus 2:
#    L:
#      id: 1
#      Position: 1030
#    R:
#      id: 2
#      Position: 1000
#  Bus 3:
#    L:
#      id: 1
#      Position: 1030
#    R:
#      id: 2
#      Position: 1000
  


Powerboard_Scaling_Factor:
  -  # 1
    Current_Factor: 1.0
    Current_Offset: 0.0
    Voltage_Factor: 1.0
    Voltage_Offset: 0.0
  -  # 2
    Current_Factor: 1.0
    Current_Offset: 0.0
    Voltage_Factor: 1.0
    Voltage_Offset: 0.0
  -  # L1
    Current_Factor: 1.0
    Current_Offset: 0.0
    Voltage_Factor: 1.0
    Voltage_Offset: 0.0
  -  # L2
    Current_Factor: 1.0
    Current_Offset: 0.0
    Voltage_Factor: 1.0
    Voltage_Offset: 0.0
  -  # L3
    Current_Factor: 1.0
    Current_Offset: 0.0
    Voltage_Factor: 1.0
    Voltage_Offset: 0.0
  -  # R1
    Current_Factor: 1.0
    Current_Offset: 0.0
    Voltage_Factor: 1.0
    Voltage_Offset: 0.0
  -  # R2
    Current_Factor: 1.0
    Current_Offset: 0.0
    Voltage_Factor: 1.0
    Voltage_Offset: 0.0
  -  # R3
    Current_Factor: 1.0
    Current_Offset: 0.0
    Voltage_Factor: 1.0
    Voltage_Offset: 0.0
  -  # Bus 
    Current_Factor: 1.0
    Current_Offset: 0.0
    Voltage_Factor: 1.0
    Voltage_Offset: 0.0
