// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: Power.proto
// Protobuf C++ Version: 6.31.0

#ifndef Power_2eproto_2epb_2eh
#define Power_2eproto_2epb_2eh

#include <limits>
#include <string>
#include <type_traits>
#include <utility>

#include "google/protobuf/runtime_version.h"
#if PROTOBUF_VERSION != 6031000
#error "Protobuf C++ gencode is built with an incompatible version of"
#error "Protobuf C++ headers/runtime. See"
#error "https://protobuf.dev/support/cross-version-runtime-guarantee/#cpp"
#endif
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/arena.h"
#include "google/protobuf/arenastring.h"
#include "google/protobuf/generated_message_tctable_decl.h"
#include "google/protobuf/generated_message_util.h"
#include "google/protobuf/metadata_lite.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/message.h"
#include "google/protobuf/message_lite.h"
#include "google/protobuf/repeated_field.h"  // IWYU pragma: export
#include "google/protobuf/extension_set.h"  // IWYU pragma: export
#include "google/protobuf/generated_enum_reflection.h"
#include "google/protobuf/unknown_field_set.h"
#include "std.pb.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"

#define PROTOBUF_INTERNAL_EXPORT_Power_2eproto

namespace google {
namespace protobuf {
namespace internal {
template <typename T>
::absl::string_view GetAnyMessageName();
}  // namespace internal
}  // namespace protobuf
}  // namespace google

// Internal implementation detail -- do not use these members.
struct TableStruct_Power_2eproto {
  static const ::uint32_t offsets[];
};
extern "C" {
extern const ::google::protobuf::internal::DescriptorTable descriptor_table_Power_2eproto;
}  // extern "C"
namespace power_msg {
enum ROBOTMODE : int;
extern const uint32_t ROBOTMODE_internal_data_[];
class PowerCmdStamped;
struct PowerCmdStampedDefaultTypeInternal;
extern PowerCmdStampedDefaultTypeInternal _PowerCmdStamped_default_instance_;
extern const ::google::protobuf::internal::ClassDataFull PowerCmdStamped_class_data_;
class PowerStateStamped;
struct PowerStateStampedDefaultTypeInternal;
extern PowerStateStampedDefaultTypeInternal _PowerStateStamped_default_instance_;
extern const ::google::protobuf::internal::ClassDataFull PowerStateStamped_class_data_;
}  // namespace power_msg
namespace google {
namespace protobuf {
template <>
internal::EnumTraitsT<::power_msg::ROBOTMODE_internal_data_>
    internal::EnumTraitsImpl::value<::power_msg::ROBOTMODE>;
}  // namespace protobuf
}  // namespace google

namespace power_msg {
enum ROBOTMODE : int {
  REST_MODE = 0,
  SET_ZERO = 1,
  HALL_CALIBRATE = 2,
  MOTOR_MODE = 3,
  CONFIG_MODE = 4,
  ROBOTMODE_INT_MIN_SENTINEL_DO_NOT_USE_ =
      ::std::numeric_limits<::int32_t>::min(),
  ROBOTMODE_INT_MAX_SENTINEL_DO_NOT_USE_ =
      ::std::numeric_limits<::int32_t>::max(),
};

extern const uint32_t ROBOTMODE_internal_data_[];
inline constexpr ROBOTMODE ROBOTMODE_MIN =
    static_cast<ROBOTMODE>(0);
inline constexpr ROBOTMODE ROBOTMODE_MAX =
    static_cast<ROBOTMODE>(4);
inline bool ROBOTMODE_IsValid(int value) {
  return 0 <= value && value <= 4;
}
inline constexpr int ROBOTMODE_ARRAYSIZE = 4 + 1;
const ::google::protobuf::EnumDescriptor* PROTOBUF_NONNULL ROBOTMODE_descriptor();
template <typename T>
const ::std::string& ROBOTMODE_Name(T value) {
  static_assert(::std::is_same<T, ROBOTMODE>::value ||
                    ::std::is_integral<T>::value,
                "Incorrect type passed to ROBOTMODE_Name().");
  return ROBOTMODE_Name(static_cast<ROBOTMODE>(value));
}
template <>
inline const ::std::string& ROBOTMODE_Name(ROBOTMODE value) {
  return ::google::protobuf::internal::NameOfDenseEnum<ROBOTMODE_descriptor, 0, 4>(
      static_cast<int>(value));
}
inline bool ROBOTMODE_Parse(
    ::absl::string_view name, ROBOTMODE* PROTOBUF_NONNULL value) {
  return ::google::protobuf::internal::ParseNamedEnum<ROBOTMODE>(ROBOTMODE_descriptor(), name,
                                           value);
}

// ===================================================================


// -------------------------------------------------------------------

class PowerStateStamped final : public ::google::protobuf::Message
/* @@protoc_insertion_point(class_definition:power_msg.PowerStateStamped) */ {
 public:
  inline PowerStateStamped() : PowerStateStamped(nullptr) {}
  ~PowerStateStamped() PROTOBUF_FINAL;

#if defined(PROTOBUF_CUSTOM_VTABLE)
  void operator delete(PowerStateStamped* PROTOBUF_NONNULL msg, std::destroying_delete_t) {
    SharedDtor(*msg);
    ::google::protobuf::internal::SizedDelete(msg, sizeof(PowerStateStamped));
  }
#endif

  template <typename = void>
  explicit PROTOBUF_CONSTEXPR PowerStateStamped(::google::protobuf::internal::ConstantInitialized);

  inline PowerStateStamped(const PowerStateStamped& from) : PowerStateStamped(nullptr, from) {}
  inline PowerStateStamped(PowerStateStamped&& from) noexcept
      : PowerStateStamped(nullptr, ::std::move(from)) {}
  inline PowerStateStamped& operator=(const PowerStateStamped& from) {
    CopyFrom(from);
    return *this;
  }
  inline PowerStateStamped& operator=(PowerStateStamped&& from) noexcept {
    if (this == &from) return *this;
    if (::google::protobuf::internal::CanMoveWithInternalSwap(GetArena(), from.GetArena())) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  inline ::google::protobuf::UnknownFieldSet* PROTOBUF_NONNULL mutable_unknown_fields()
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL descriptor() {
    return GetDescriptor();
  }
  static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::google::protobuf::Reflection* PROTOBUF_NONNULL GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const PowerStateStamped& default_instance() {
    return *reinterpret_cast<const PowerStateStamped*>(
        &_PowerStateStamped_default_instance_);
  }
  static constexpr int kIndexInFileMessages = 1;
  friend void swap(PowerStateStamped& a, PowerStateStamped& b) { a.Swap(&b); }
  inline void Swap(PowerStateStamped* PROTOBUF_NONNULL other) {
    if (other == this) return;
    if (::google::protobuf::internal::CanUseInternalSwap(GetArena(), other->GetArena())) {
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(PowerStateStamped* PROTOBUF_NONNULL other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  PowerStateStamped* PROTOBUF_NONNULL New(::google::protobuf::Arena* PROTOBUF_NULLABLE arena = nullptr) const {
    return ::google::protobuf::Message::DefaultConstruct<PowerStateStamped>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const PowerStateStamped& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom(const PowerStateStamped& from) { PowerStateStamped::MergeImpl(*this, from); }

  private:
  static void MergeImpl(::google::protobuf::MessageLite& to_msg,
                        const ::google::protobuf::MessageLite& from_msg);

  public:
  bool IsInitialized() const {
    return true;
  }
  ABSL_ATTRIBUTE_REINITIALIZES void Clear() PROTOBUF_FINAL;
  #if defined(PROTOBUF_CUSTOM_VTABLE)
  private:
  static ::size_t ByteSizeLong(const ::google::protobuf::MessageLite& msg);
  static ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      const ::google::protobuf::MessageLite& msg, ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream);

  public:
  ::size_t ByteSizeLong() const { return ByteSizeLong(*this); }
  ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
    return _InternalSerialize(*this, target, stream);
  }
  #else   // PROTOBUF_CUSTOM_VTABLE
  ::size_t ByteSizeLong() const final;
  ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const final;
  #endif  // PROTOBUF_CUSTOM_VTABLE
  int GetCachedSize() const { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static void SharedDtor(MessageLite& self);
  void InternalSwap(PowerStateStamped* PROTOBUF_NONNULL other);
 private:
  template <typename T>
  friend ::absl::string_view(::google::protobuf::internal::GetAnyMessageName)();
  static ::absl::string_view FullMessageName() { return "power_msg.PowerStateStamped"; }

 protected:
  explicit PowerStateStamped(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  PowerStateStamped(::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const PowerStateStamped& from);
  PowerStateStamped(
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, PowerStateStamped&& from) noexcept
      : PowerStateStamped(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL GetClassData() const PROTOBUF_FINAL;
  static void* PROTOBUF_NONNULL PlacementNew_(
      const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static constexpr auto InternalNewImpl_();

 public:
  static constexpr auto InternalGenerateClassData_();

  ::google::protobuf::Metadata GetMetadata() const;
  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------
  enum : int {
    kHeaderFieldNumber = 1,
    kDigitalFieldNumber = 2,
    kSignalFieldNumber = 3,
    kPowerFieldNumber = 4,
    kCleanFieldNumber = 5,
    kRobotModeFieldNumber = 6,
    kV0FieldNumber = 7,
    kI0FieldNumber = 8,
    kV1FieldNumber = 9,
    kI1FieldNumber = 10,
    kV2FieldNumber = 11,
    kI2FieldNumber = 12,
    kV3FieldNumber = 13,
    kI3FieldNumber = 14,
    kV4FieldNumber = 15,
    kI4FieldNumber = 16,
    kV5FieldNumber = 17,
    kI5FieldNumber = 18,
    kV6FieldNumber = 19,
    kI6FieldNumber = 20,
  };
  // .std_msg.Header header = 1;
  bool has_header() const;
  void clear_header() ;
  const ::std_msg::Header& header() const;
  [[nodiscard]] ::std_msg::Header* PROTOBUF_NULLABLE release_header();
  ::std_msg::Header* PROTOBUF_NONNULL mutable_header();
  void set_allocated_header(::std_msg::Header* PROTOBUF_NULLABLE value);
  void unsafe_arena_set_allocated_header(::std_msg::Header* PROTOBUF_NULLABLE value);
  ::std_msg::Header* PROTOBUF_NULLABLE unsafe_arena_release_header();

  private:
  const ::std_msg::Header& _internal_header() const;
  ::std_msg::Header* PROTOBUF_NONNULL _internal_mutable_header();

  public:
  // bool digital = 2;
  void clear_digital() ;
  bool digital() const;
  void set_digital(bool value);

  private:
  bool _internal_digital() const;
  void _internal_set_digital(bool value);

  public:
  // bool signal = 3;
  void clear_signal() ;
  bool signal() const;
  void set_signal(bool value);

  private:
  bool _internal_signal() const;
  void _internal_set_signal(bool value);

  public:
  // bool power = 4;
  void clear_power() ;
  bool power() const;
  void set_power(bool value);

  private:
  bool _internal_power() const;
  void _internal_set_power(bool value);

  public:
  // bool clean = 5;
  void clear_clean() ;
  bool clean() const;
  void set_clean(bool value);

  private:
  bool _internal_clean() const;
  void _internal_set_clean(bool value);

  public:
  // .power_msg.ROBOTMODE robot_mode = 6;
  void clear_robot_mode() ;
  ::power_msg::ROBOTMODE robot_mode() const;
  void set_robot_mode(::power_msg::ROBOTMODE value);

  private:
  ::power_msg::ROBOTMODE _internal_robot_mode() const;
  void _internal_set_robot_mode(::power_msg::ROBOTMODE value);

  public:
  // double v_0 = 7;
  void clear_v_0() ;
  double v_0() const;
  void set_v_0(double value);

  private:
  double _internal_v_0() const;
  void _internal_set_v_0(double value);

  public:
  // double i_0 = 8;
  void clear_i_0() ;
  double i_0() const;
  void set_i_0(double value);

  private:
  double _internal_i_0() const;
  void _internal_set_i_0(double value);

  public:
  // double v_1 = 9;
  void clear_v_1() ;
  double v_1() const;
  void set_v_1(double value);

  private:
  double _internal_v_1() const;
  void _internal_set_v_1(double value);

  public:
  // double i_1 = 10;
  void clear_i_1() ;
  double i_1() const;
  void set_i_1(double value);

  private:
  double _internal_i_1() const;
  void _internal_set_i_1(double value);

  public:
  // double v_2 = 11;
  void clear_v_2() ;
  double v_2() const;
  void set_v_2(double value);

  private:
  double _internal_v_2() const;
  void _internal_set_v_2(double value);

  public:
  // double i_2 = 12;
  void clear_i_2() ;
  double i_2() const;
  void set_i_2(double value);

  private:
  double _internal_i_2() const;
  void _internal_set_i_2(double value);

  public:
  // double v_3 = 13;
  void clear_v_3() ;
  double v_3() const;
  void set_v_3(double value);

  private:
  double _internal_v_3() const;
  void _internal_set_v_3(double value);

  public:
  // double i_3 = 14;
  void clear_i_3() ;
  double i_3() const;
  void set_i_3(double value);

  private:
  double _internal_i_3() const;
  void _internal_set_i_3(double value);

  public:
  // double v_4 = 15;
  void clear_v_4() ;
  double v_4() const;
  void set_v_4(double value);

  private:
  double _internal_v_4() const;
  void _internal_set_v_4(double value);

  public:
  // double i_4 = 16;
  void clear_i_4() ;
  double i_4() const;
  void set_i_4(double value);

  private:
  double _internal_i_4() const;
  void _internal_set_i_4(double value);

  public:
  // double v_5 = 17;
  void clear_v_5() ;
  double v_5() const;
  void set_v_5(double value);

  private:
  double _internal_v_5() const;
  void _internal_set_v_5(double value);

  public:
  // double i_5 = 18;
  void clear_i_5() ;
  double i_5() const;
  void set_i_5(double value);

  private:
  double _internal_i_5() const;
  void _internal_set_i_5(double value);

  public:
  // double v_6 = 19;
  void clear_v_6() ;
  double v_6() const;
  void set_v_6(double value);

  private:
  double _internal_v_6() const;
  void _internal_set_v_6(double value);

  public:
  // double i_6 = 20;
  void clear_i_6() ;
  double i_6() const;
  void set_i_6(double value);

  private:
  double _internal_i_6() const;
  void _internal_set_i_6(double value);

  public:
  // @@protoc_insertion_point(class_scope:power_msg.PowerStateStamped)
 private:
  class _Internal;
  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<5, 20,
                                   1, 0,
                                   2>
      _table_;

  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(::google::protobuf::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Impl_& from,
        const PowerStateStamped& from_msg);
    ::google::protobuf::internal::HasBits<1> _has_bits_;
    ::google::protobuf::internal::CachedSize _cached_size_;
    ::std_msg::Header* PROTOBUF_NULLABLE header_;
    bool digital_;
    bool signal_;
    bool power_;
    bool clean_;
    int robot_mode_;
    double v_0_;
    double i_0_;
    double v_1_;
    double i_1_;
    double v_2_;
    double i_2_;
    double v_3_;
    double i_3_;
    double v_4_;
    double i_4_;
    double v_5_;
    double i_5_;
    double v_6_;
    double i_6_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_Power_2eproto;
};

extern const ::google::protobuf::internal::ClassDataFull PowerStateStamped_class_data_;
// -------------------------------------------------------------------

class PowerCmdStamped final : public ::google::protobuf::Message
/* @@protoc_insertion_point(class_definition:power_msg.PowerCmdStamped) */ {
 public:
  inline PowerCmdStamped() : PowerCmdStamped(nullptr) {}
  ~PowerCmdStamped() PROTOBUF_FINAL;

#if defined(PROTOBUF_CUSTOM_VTABLE)
  void operator delete(PowerCmdStamped* PROTOBUF_NONNULL msg, std::destroying_delete_t) {
    SharedDtor(*msg);
    ::google::protobuf::internal::SizedDelete(msg, sizeof(PowerCmdStamped));
  }
#endif

  template <typename = void>
  explicit PROTOBUF_CONSTEXPR PowerCmdStamped(::google::protobuf::internal::ConstantInitialized);

  inline PowerCmdStamped(const PowerCmdStamped& from) : PowerCmdStamped(nullptr, from) {}
  inline PowerCmdStamped(PowerCmdStamped&& from) noexcept
      : PowerCmdStamped(nullptr, ::std::move(from)) {}
  inline PowerCmdStamped& operator=(const PowerCmdStamped& from) {
    CopyFrom(from);
    return *this;
  }
  inline PowerCmdStamped& operator=(PowerCmdStamped&& from) noexcept {
    if (this == &from) return *this;
    if (::google::protobuf::internal::CanMoveWithInternalSwap(GetArena(), from.GetArena())) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  inline ::google::protobuf::UnknownFieldSet* PROTOBUF_NONNULL mutable_unknown_fields()
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL descriptor() {
    return GetDescriptor();
  }
  static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::google::protobuf::Reflection* PROTOBUF_NONNULL GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const PowerCmdStamped& default_instance() {
    return *reinterpret_cast<const PowerCmdStamped*>(
        &_PowerCmdStamped_default_instance_);
  }
  static constexpr int kIndexInFileMessages = 0;
  friend void swap(PowerCmdStamped& a, PowerCmdStamped& b) { a.Swap(&b); }
  inline void Swap(PowerCmdStamped* PROTOBUF_NONNULL other) {
    if (other == this) return;
    if (::google::protobuf::internal::CanUseInternalSwap(GetArena(), other->GetArena())) {
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(PowerCmdStamped* PROTOBUF_NONNULL other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  PowerCmdStamped* PROTOBUF_NONNULL New(::google::protobuf::Arena* PROTOBUF_NULLABLE arena = nullptr) const {
    return ::google::protobuf::Message::DefaultConstruct<PowerCmdStamped>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const PowerCmdStamped& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom(const PowerCmdStamped& from) { PowerCmdStamped::MergeImpl(*this, from); }

  private:
  static void MergeImpl(::google::protobuf::MessageLite& to_msg,
                        const ::google::protobuf::MessageLite& from_msg);

  public:
  bool IsInitialized() const {
    return true;
  }
  ABSL_ATTRIBUTE_REINITIALIZES void Clear() PROTOBUF_FINAL;
  #if defined(PROTOBUF_CUSTOM_VTABLE)
  private:
  static ::size_t ByteSizeLong(const ::google::protobuf::MessageLite& msg);
  static ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      const ::google::protobuf::MessageLite& msg, ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream);

  public:
  ::size_t ByteSizeLong() const { return ByteSizeLong(*this); }
  ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
    return _InternalSerialize(*this, target, stream);
  }
  #else   // PROTOBUF_CUSTOM_VTABLE
  ::size_t ByteSizeLong() const final;
  ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const final;
  #endif  // PROTOBUF_CUSTOM_VTABLE
  int GetCachedSize() const { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static void SharedDtor(MessageLite& self);
  void InternalSwap(PowerCmdStamped* PROTOBUF_NONNULL other);
 private:
  template <typename T>
  friend ::absl::string_view(::google::protobuf::internal::GetAnyMessageName)();
  static ::absl::string_view FullMessageName() { return "power_msg.PowerCmdStamped"; }

 protected:
  explicit PowerCmdStamped(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  PowerCmdStamped(::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const PowerCmdStamped& from);
  PowerCmdStamped(
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, PowerCmdStamped&& from) noexcept
      : PowerCmdStamped(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL GetClassData() const PROTOBUF_FINAL;
  static void* PROTOBUF_NONNULL PlacementNew_(
      const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static constexpr auto InternalNewImpl_();

 public:
  static constexpr auto InternalGenerateClassData_();

  ::google::protobuf::Metadata GetMetadata() const;
  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------
  enum : int {
    kHeaderFieldNumber = 1,
    kDigitalFieldNumber = 2,
    kSignalFieldNumber = 3,
    kPowerFieldNumber = 4,
    kCleanFieldNumber = 5,
    kTriggerFieldNumber = 6,
    kRobotModeFieldNumber = 7,
  };
  // .std_msg.Header header = 1;
  bool has_header() const;
  void clear_header() ;
  const ::std_msg::Header& header() const;
  [[nodiscard]] ::std_msg::Header* PROTOBUF_NULLABLE release_header();
  ::std_msg::Header* PROTOBUF_NONNULL mutable_header();
  void set_allocated_header(::std_msg::Header* PROTOBUF_NULLABLE value);
  void unsafe_arena_set_allocated_header(::std_msg::Header* PROTOBUF_NULLABLE value);
  ::std_msg::Header* PROTOBUF_NULLABLE unsafe_arena_release_header();

  private:
  const ::std_msg::Header& _internal_header() const;
  ::std_msg::Header* PROTOBUF_NONNULL _internal_mutable_header();

  public:
  // bool digital = 2;
  void clear_digital() ;
  bool digital() const;
  void set_digital(bool value);

  private:
  bool _internal_digital() const;
  void _internal_set_digital(bool value);

  public:
  // bool signal = 3;
  void clear_signal() ;
  bool signal() const;
  void set_signal(bool value);

  private:
  bool _internal_signal() const;
  void _internal_set_signal(bool value);

  public:
  // bool power = 4;
  void clear_power() ;
  bool power() const;
  void set_power(bool value);

  private:
  bool _internal_power() const;
  void _internal_set_power(bool value);

  public:
  // bool clean = 5;
  void clear_clean() ;
  bool clean() const;
  void set_clean(bool value);

  private:
  bool _internal_clean() const;
  void _internal_set_clean(bool value);

  public:
  // bool trigger = 6;
  void clear_trigger() ;
  bool trigger() const;
  void set_trigger(bool value);

  private:
  bool _internal_trigger() const;
  void _internal_set_trigger(bool value);

  public:
  // .power_msg.ROBOTMODE robot_mode = 7;
  void clear_robot_mode() ;
  ::power_msg::ROBOTMODE robot_mode() const;
  void set_robot_mode(::power_msg::ROBOTMODE value);

  private:
  ::power_msg::ROBOTMODE _internal_robot_mode() const;
  void _internal_set_robot_mode(::power_msg::ROBOTMODE value);

  public:
  // @@protoc_insertion_point(class_scope:power_msg.PowerCmdStamped)
 private:
  class _Internal;
  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<3, 7,
                                   1, 0,
                                   2>
      _table_;

  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(::google::protobuf::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Impl_& from,
        const PowerCmdStamped& from_msg);
    ::google::protobuf::internal::HasBits<1> _has_bits_;
    ::google::protobuf::internal::CachedSize _cached_size_;
    ::std_msg::Header* PROTOBUF_NULLABLE header_;
    bool digital_;
    bool signal_;
    bool power_;
    bool clean_;
    bool trigger_;
    int robot_mode_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_Power_2eproto;
};

extern const ::google::protobuf::internal::ClassDataFull PowerCmdStamped_class_data_;

// ===================================================================




// ===================================================================


#ifdef __GNUC__
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// -------------------------------------------------------------------

// PowerCmdStamped

// .std_msg.Header header = 1;
inline bool PowerCmdStamped::has_header() const {
  bool value = (_impl_._has_bits_[0] & 0x00000001u) != 0;
  PROTOBUF_ASSUME(!value || _impl_.header_ != nullptr);
  return value;
}
inline const ::std_msg::Header& PowerCmdStamped::_internal_header() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  const ::std_msg::Header* p = _impl_.header_;
  return p != nullptr ? *p : reinterpret_cast<const ::std_msg::Header&>(::std_msg::_Header_default_instance_);
}
inline const ::std_msg::Header& PowerCmdStamped::header() const ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:power_msg.PowerCmdStamped.header)
  return _internal_header();
}
inline void PowerCmdStamped::unsafe_arena_set_allocated_header(
    ::std_msg::Header* PROTOBUF_NULLABLE value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (GetArena() == nullptr) {
    delete reinterpret_cast<::google::protobuf::MessageLite*>(_impl_.header_);
  }
  _impl_.header_ = reinterpret_cast<::std_msg::Header*>(value);
  if (value != nullptr) {
    _impl_._has_bits_[0] |= 0x00000001u;
  } else {
    _impl_._has_bits_[0] &= ~0x00000001u;
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:power_msg.PowerCmdStamped.header)
}
inline ::std_msg::Header* PROTOBUF_NULLABLE PowerCmdStamped::release_header() {
  ::google::protobuf::internal::TSanWrite(&_impl_);

  _impl_._has_bits_[0] &= ~0x00000001u;
  ::std_msg::Header* released = _impl_.header_;
  _impl_.header_ = nullptr;
  if (::google::protobuf::internal::DebugHardenForceCopyInRelease()) {
    auto* old = reinterpret_cast<::google::protobuf::MessageLite*>(released);
    released = ::google::protobuf::internal::DuplicateIfNonNull(released);
    if (GetArena() == nullptr) {
      delete old;
    }
  } else {
    if (GetArena() != nullptr) {
      released = ::google::protobuf::internal::DuplicateIfNonNull(released);
    }
  }
  return released;
}
inline ::std_msg::Header* PROTOBUF_NULLABLE PowerCmdStamped::unsafe_arena_release_header() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:power_msg.PowerCmdStamped.header)

  _impl_._has_bits_[0] &= ~0x00000001u;
  ::std_msg::Header* temp = _impl_.header_;
  _impl_.header_ = nullptr;
  return temp;
}
inline ::std_msg::Header* PROTOBUF_NONNULL PowerCmdStamped::_internal_mutable_header() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (_impl_.header_ == nullptr) {
    auto* p = ::google::protobuf::Message::DefaultConstruct<::std_msg::Header>(GetArena());
    _impl_.header_ = reinterpret_cast<::std_msg::Header*>(p);
  }
  return _impl_.header_;
}
inline ::std_msg::Header* PROTOBUF_NONNULL PowerCmdStamped::mutable_header()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  _impl_._has_bits_[0] |= 0x00000001u;
  ::std_msg::Header* _msg = _internal_mutable_header();
  // @@protoc_insertion_point(field_mutable:power_msg.PowerCmdStamped.header)
  return _msg;
}
inline void PowerCmdStamped::set_allocated_header(::std_msg::Header* PROTOBUF_NULLABLE value) {
  ::google::protobuf::Arena* message_arena = GetArena();
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (message_arena == nullptr) {
    delete reinterpret_cast<::google::protobuf::MessageLite*>(_impl_.header_);
  }

  if (value != nullptr) {
    ::google::protobuf::Arena* submessage_arena = reinterpret_cast<::google::protobuf::Message*>(value)->GetArena();
    if (message_arena != submessage_arena) {
      value = ::google::protobuf::internal::GetOwnedMessage(message_arena, value, submessage_arena);
    }
    _impl_._has_bits_[0] |= 0x00000001u;
  } else {
    _impl_._has_bits_[0] &= ~0x00000001u;
  }

  _impl_.header_ = reinterpret_cast<::std_msg::Header*>(value);
  // @@protoc_insertion_point(field_set_allocated:power_msg.PowerCmdStamped.header)
}

// bool digital = 2;
inline void PowerCmdStamped::clear_digital() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.digital_ = false;
  _impl_._has_bits_[0] &= ~0x00000002u;
}
inline bool PowerCmdStamped::digital() const {
  // @@protoc_insertion_point(field_get:power_msg.PowerCmdStamped.digital)
  return _internal_digital();
}
inline void PowerCmdStamped::set_digital(bool value) {
  _internal_set_digital(value);
  _impl_._has_bits_[0] |= 0x00000002u;
  // @@protoc_insertion_point(field_set:power_msg.PowerCmdStamped.digital)
}
inline bool PowerCmdStamped::_internal_digital() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.digital_;
}
inline void PowerCmdStamped::_internal_set_digital(bool value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.digital_ = value;
}

// bool signal = 3;
inline void PowerCmdStamped::clear_signal() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.signal_ = false;
  _impl_._has_bits_[0] &= ~0x00000004u;
}
inline bool PowerCmdStamped::signal() const {
  // @@protoc_insertion_point(field_get:power_msg.PowerCmdStamped.signal)
  return _internal_signal();
}
inline void PowerCmdStamped::set_signal(bool value) {
  _internal_set_signal(value);
  _impl_._has_bits_[0] |= 0x00000004u;
  // @@protoc_insertion_point(field_set:power_msg.PowerCmdStamped.signal)
}
inline bool PowerCmdStamped::_internal_signal() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.signal_;
}
inline void PowerCmdStamped::_internal_set_signal(bool value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.signal_ = value;
}

// bool power = 4;
inline void PowerCmdStamped::clear_power() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.power_ = false;
  _impl_._has_bits_[0] &= ~0x00000008u;
}
inline bool PowerCmdStamped::power() const {
  // @@protoc_insertion_point(field_get:power_msg.PowerCmdStamped.power)
  return _internal_power();
}
inline void PowerCmdStamped::set_power(bool value) {
  _internal_set_power(value);
  _impl_._has_bits_[0] |= 0x00000008u;
  // @@protoc_insertion_point(field_set:power_msg.PowerCmdStamped.power)
}
inline bool PowerCmdStamped::_internal_power() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.power_;
}
inline void PowerCmdStamped::_internal_set_power(bool value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.power_ = value;
}

// bool clean = 5;
inline void PowerCmdStamped::clear_clean() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.clean_ = false;
  _impl_._has_bits_[0] &= ~0x00000010u;
}
inline bool PowerCmdStamped::clean() const {
  // @@protoc_insertion_point(field_get:power_msg.PowerCmdStamped.clean)
  return _internal_clean();
}
inline void PowerCmdStamped::set_clean(bool value) {
  _internal_set_clean(value);
  _impl_._has_bits_[0] |= 0x00000010u;
  // @@protoc_insertion_point(field_set:power_msg.PowerCmdStamped.clean)
}
inline bool PowerCmdStamped::_internal_clean() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.clean_;
}
inline void PowerCmdStamped::_internal_set_clean(bool value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.clean_ = value;
}

// bool trigger = 6;
inline void PowerCmdStamped::clear_trigger() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.trigger_ = false;
  _impl_._has_bits_[0] &= ~0x00000020u;
}
inline bool PowerCmdStamped::trigger() const {
  // @@protoc_insertion_point(field_get:power_msg.PowerCmdStamped.trigger)
  return _internal_trigger();
}
inline void PowerCmdStamped::set_trigger(bool value) {
  _internal_set_trigger(value);
  _impl_._has_bits_[0] |= 0x00000020u;
  // @@protoc_insertion_point(field_set:power_msg.PowerCmdStamped.trigger)
}
inline bool PowerCmdStamped::_internal_trigger() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.trigger_;
}
inline void PowerCmdStamped::_internal_set_trigger(bool value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.trigger_ = value;
}

// .power_msg.ROBOTMODE robot_mode = 7;
inline void PowerCmdStamped::clear_robot_mode() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.robot_mode_ = 0;
  _impl_._has_bits_[0] &= ~0x00000040u;
}
inline ::power_msg::ROBOTMODE PowerCmdStamped::robot_mode() const {
  // @@protoc_insertion_point(field_get:power_msg.PowerCmdStamped.robot_mode)
  return _internal_robot_mode();
}
inline void PowerCmdStamped::set_robot_mode(::power_msg::ROBOTMODE value) {
  _internal_set_robot_mode(value);
  _impl_._has_bits_[0] |= 0x00000040u;
  // @@protoc_insertion_point(field_set:power_msg.PowerCmdStamped.robot_mode)
}
inline ::power_msg::ROBOTMODE PowerCmdStamped::_internal_robot_mode() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return static_cast<::power_msg::ROBOTMODE>(_impl_.robot_mode_);
}
inline void PowerCmdStamped::_internal_set_robot_mode(::power_msg::ROBOTMODE value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.robot_mode_ = value;
}

// -------------------------------------------------------------------

// PowerStateStamped

// .std_msg.Header header = 1;
inline bool PowerStateStamped::has_header() const {
  bool value = (_impl_._has_bits_[0] & 0x00000001u) != 0;
  PROTOBUF_ASSUME(!value || _impl_.header_ != nullptr);
  return value;
}
inline const ::std_msg::Header& PowerStateStamped::_internal_header() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  const ::std_msg::Header* p = _impl_.header_;
  return p != nullptr ? *p : reinterpret_cast<const ::std_msg::Header&>(::std_msg::_Header_default_instance_);
}
inline const ::std_msg::Header& PowerStateStamped::header() const ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:power_msg.PowerStateStamped.header)
  return _internal_header();
}
inline void PowerStateStamped::unsafe_arena_set_allocated_header(
    ::std_msg::Header* PROTOBUF_NULLABLE value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (GetArena() == nullptr) {
    delete reinterpret_cast<::google::protobuf::MessageLite*>(_impl_.header_);
  }
  _impl_.header_ = reinterpret_cast<::std_msg::Header*>(value);
  if (value != nullptr) {
    _impl_._has_bits_[0] |= 0x00000001u;
  } else {
    _impl_._has_bits_[0] &= ~0x00000001u;
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:power_msg.PowerStateStamped.header)
}
inline ::std_msg::Header* PROTOBUF_NULLABLE PowerStateStamped::release_header() {
  ::google::protobuf::internal::TSanWrite(&_impl_);

  _impl_._has_bits_[0] &= ~0x00000001u;
  ::std_msg::Header* released = _impl_.header_;
  _impl_.header_ = nullptr;
  if (::google::protobuf::internal::DebugHardenForceCopyInRelease()) {
    auto* old = reinterpret_cast<::google::protobuf::MessageLite*>(released);
    released = ::google::protobuf::internal::DuplicateIfNonNull(released);
    if (GetArena() == nullptr) {
      delete old;
    }
  } else {
    if (GetArena() != nullptr) {
      released = ::google::protobuf::internal::DuplicateIfNonNull(released);
    }
  }
  return released;
}
inline ::std_msg::Header* PROTOBUF_NULLABLE PowerStateStamped::unsafe_arena_release_header() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:power_msg.PowerStateStamped.header)

  _impl_._has_bits_[0] &= ~0x00000001u;
  ::std_msg::Header* temp = _impl_.header_;
  _impl_.header_ = nullptr;
  return temp;
}
inline ::std_msg::Header* PROTOBUF_NONNULL PowerStateStamped::_internal_mutable_header() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (_impl_.header_ == nullptr) {
    auto* p = ::google::protobuf::Message::DefaultConstruct<::std_msg::Header>(GetArena());
    _impl_.header_ = reinterpret_cast<::std_msg::Header*>(p);
  }
  return _impl_.header_;
}
inline ::std_msg::Header* PROTOBUF_NONNULL PowerStateStamped::mutable_header()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  _impl_._has_bits_[0] |= 0x00000001u;
  ::std_msg::Header* _msg = _internal_mutable_header();
  // @@protoc_insertion_point(field_mutable:power_msg.PowerStateStamped.header)
  return _msg;
}
inline void PowerStateStamped::set_allocated_header(::std_msg::Header* PROTOBUF_NULLABLE value) {
  ::google::protobuf::Arena* message_arena = GetArena();
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (message_arena == nullptr) {
    delete reinterpret_cast<::google::protobuf::MessageLite*>(_impl_.header_);
  }

  if (value != nullptr) {
    ::google::protobuf::Arena* submessage_arena = reinterpret_cast<::google::protobuf::Message*>(value)->GetArena();
    if (message_arena != submessage_arena) {
      value = ::google::protobuf::internal::GetOwnedMessage(message_arena, value, submessage_arena);
    }
    _impl_._has_bits_[0] |= 0x00000001u;
  } else {
    _impl_._has_bits_[0] &= ~0x00000001u;
  }

  _impl_.header_ = reinterpret_cast<::std_msg::Header*>(value);
  // @@protoc_insertion_point(field_set_allocated:power_msg.PowerStateStamped.header)
}

// bool digital = 2;
inline void PowerStateStamped::clear_digital() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.digital_ = false;
  _impl_._has_bits_[0] &= ~0x00000002u;
}
inline bool PowerStateStamped::digital() const {
  // @@protoc_insertion_point(field_get:power_msg.PowerStateStamped.digital)
  return _internal_digital();
}
inline void PowerStateStamped::set_digital(bool value) {
  _internal_set_digital(value);
  _impl_._has_bits_[0] |= 0x00000002u;
  // @@protoc_insertion_point(field_set:power_msg.PowerStateStamped.digital)
}
inline bool PowerStateStamped::_internal_digital() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.digital_;
}
inline void PowerStateStamped::_internal_set_digital(bool value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.digital_ = value;
}

// bool signal = 3;
inline void PowerStateStamped::clear_signal() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.signal_ = false;
  _impl_._has_bits_[0] &= ~0x00000004u;
}
inline bool PowerStateStamped::signal() const {
  // @@protoc_insertion_point(field_get:power_msg.PowerStateStamped.signal)
  return _internal_signal();
}
inline void PowerStateStamped::set_signal(bool value) {
  _internal_set_signal(value);
  _impl_._has_bits_[0] |= 0x00000004u;
  // @@protoc_insertion_point(field_set:power_msg.PowerStateStamped.signal)
}
inline bool PowerStateStamped::_internal_signal() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.signal_;
}
inline void PowerStateStamped::_internal_set_signal(bool value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.signal_ = value;
}

// bool power = 4;
inline void PowerStateStamped::clear_power() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.power_ = false;
  _impl_._has_bits_[0] &= ~0x00000008u;
}
inline bool PowerStateStamped::power() const {
  // @@protoc_insertion_point(field_get:power_msg.PowerStateStamped.power)
  return _internal_power();
}
inline void PowerStateStamped::set_power(bool value) {
  _internal_set_power(value);
  _impl_._has_bits_[0] |= 0x00000008u;
  // @@protoc_insertion_point(field_set:power_msg.PowerStateStamped.power)
}
inline bool PowerStateStamped::_internal_power() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.power_;
}
inline void PowerStateStamped::_internal_set_power(bool value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.power_ = value;
}

// bool clean = 5;
inline void PowerStateStamped::clear_clean() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.clean_ = false;
  _impl_._has_bits_[0] &= ~0x00000010u;
}
inline bool PowerStateStamped::clean() const {
  // @@protoc_insertion_point(field_get:power_msg.PowerStateStamped.clean)
  return _internal_clean();
}
inline void PowerStateStamped::set_clean(bool value) {
  _internal_set_clean(value);
  _impl_._has_bits_[0] |= 0x00000010u;
  // @@protoc_insertion_point(field_set:power_msg.PowerStateStamped.clean)
}
inline bool PowerStateStamped::_internal_clean() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.clean_;
}
inline void PowerStateStamped::_internal_set_clean(bool value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.clean_ = value;
}

// .power_msg.ROBOTMODE robot_mode = 6;
inline void PowerStateStamped::clear_robot_mode() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.robot_mode_ = 0;
  _impl_._has_bits_[0] &= ~0x00000020u;
}
inline ::power_msg::ROBOTMODE PowerStateStamped::robot_mode() const {
  // @@protoc_insertion_point(field_get:power_msg.PowerStateStamped.robot_mode)
  return _internal_robot_mode();
}
inline void PowerStateStamped::set_robot_mode(::power_msg::ROBOTMODE value) {
  _internal_set_robot_mode(value);
  _impl_._has_bits_[0] |= 0x00000020u;
  // @@protoc_insertion_point(field_set:power_msg.PowerStateStamped.robot_mode)
}
inline ::power_msg::ROBOTMODE PowerStateStamped::_internal_robot_mode() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return static_cast<::power_msg::ROBOTMODE>(_impl_.robot_mode_);
}
inline void PowerStateStamped::_internal_set_robot_mode(::power_msg::ROBOTMODE value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.robot_mode_ = value;
}

// double v_0 = 7;
inline void PowerStateStamped::clear_v_0() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.v_0_ = 0;
  _impl_._has_bits_[0] &= ~0x00000040u;
}
inline double PowerStateStamped::v_0() const {
  // @@protoc_insertion_point(field_get:power_msg.PowerStateStamped.v_0)
  return _internal_v_0();
}
inline void PowerStateStamped::set_v_0(double value) {
  _internal_set_v_0(value);
  _impl_._has_bits_[0] |= 0x00000040u;
  // @@protoc_insertion_point(field_set:power_msg.PowerStateStamped.v_0)
}
inline double PowerStateStamped::_internal_v_0() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.v_0_;
}
inline void PowerStateStamped::_internal_set_v_0(double value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.v_0_ = value;
}

// double i_0 = 8;
inline void PowerStateStamped::clear_i_0() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.i_0_ = 0;
  _impl_._has_bits_[0] &= ~0x00000080u;
}
inline double PowerStateStamped::i_0() const {
  // @@protoc_insertion_point(field_get:power_msg.PowerStateStamped.i_0)
  return _internal_i_0();
}
inline void PowerStateStamped::set_i_0(double value) {
  _internal_set_i_0(value);
  _impl_._has_bits_[0] |= 0x00000080u;
  // @@protoc_insertion_point(field_set:power_msg.PowerStateStamped.i_0)
}
inline double PowerStateStamped::_internal_i_0() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.i_0_;
}
inline void PowerStateStamped::_internal_set_i_0(double value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.i_0_ = value;
}

// double v_1 = 9;
inline void PowerStateStamped::clear_v_1() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.v_1_ = 0;
  _impl_._has_bits_[0] &= ~0x00000100u;
}
inline double PowerStateStamped::v_1() const {
  // @@protoc_insertion_point(field_get:power_msg.PowerStateStamped.v_1)
  return _internal_v_1();
}
inline void PowerStateStamped::set_v_1(double value) {
  _internal_set_v_1(value);
  _impl_._has_bits_[0] |= 0x00000100u;
  // @@protoc_insertion_point(field_set:power_msg.PowerStateStamped.v_1)
}
inline double PowerStateStamped::_internal_v_1() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.v_1_;
}
inline void PowerStateStamped::_internal_set_v_1(double value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.v_1_ = value;
}

// double i_1 = 10;
inline void PowerStateStamped::clear_i_1() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.i_1_ = 0;
  _impl_._has_bits_[0] &= ~0x00000200u;
}
inline double PowerStateStamped::i_1() const {
  // @@protoc_insertion_point(field_get:power_msg.PowerStateStamped.i_1)
  return _internal_i_1();
}
inline void PowerStateStamped::set_i_1(double value) {
  _internal_set_i_1(value);
  _impl_._has_bits_[0] |= 0x00000200u;
  // @@protoc_insertion_point(field_set:power_msg.PowerStateStamped.i_1)
}
inline double PowerStateStamped::_internal_i_1() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.i_1_;
}
inline void PowerStateStamped::_internal_set_i_1(double value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.i_1_ = value;
}

// double v_2 = 11;
inline void PowerStateStamped::clear_v_2() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.v_2_ = 0;
  _impl_._has_bits_[0] &= ~0x00000400u;
}
inline double PowerStateStamped::v_2() const {
  // @@protoc_insertion_point(field_get:power_msg.PowerStateStamped.v_2)
  return _internal_v_2();
}
inline void PowerStateStamped::set_v_2(double value) {
  _internal_set_v_2(value);
  _impl_._has_bits_[0] |= 0x00000400u;
  // @@protoc_insertion_point(field_set:power_msg.PowerStateStamped.v_2)
}
inline double PowerStateStamped::_internal_v_2() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.v_2_;
}
inline void PowerStateStamped::_internal_set_v_2(double value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.v_2_ = value;
}

// double i_2 = 12;
inline void PowerStateStamped::clear_i_2() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.i_2_ = 0;
  _impl_._has_bits_[0] &= ~0x00000800u;
}
inline double PowerStateStamped::i_2() const {
  // @@protoc_insertion_point(field_get:power_msg.PowerStateStamped.i_2)
  return _internal_i_2();
}
inline void PowerStateStamped::set_i_2(double value) {
  _internal_set_i_2(value);
  _impl_._has_bits_[0] |= 0x00000800u;
  // @@protoc_insertion_point(field_set:power_msg.PowerStateStamped.i_2)
}
inline double PowerStateStamped::_internal_i_2() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.i_2_;
}
inline void PowerStateStamped::_internal_set_i_2(double value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.i_2_ = value;
}

// double v_3 = 13;
inline void PowerStateStamped::clear_v_3() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.v_3_ = 0;
  _impl_._has_bits_[0] &= ~0x00001000u;
}
inline double PowerStateStamped::v_3() const {
  // @@protoc_insertion_point(field_get:power_msg.PowerStateStamped.v_3)
  return _internal_v_3();
}
inline void PowerStateStamped::set_v_3(double value) {
  _internal_set_v_3(value);
  _impl_._has_bits_[0] |= 0x00001000u;
  // @@protoc_insertion_point(field_set:power_msg.PowerStateStamped.v_3)
}
inline double PowerStateStamped::_internal_v_3() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.v_3_;
}
inline void PowerStateStamped::_internal_set_v_3(double value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.v_3_ = value;
}

// double i_3 = 14;
inline void PowerStateStamped::clear_i_3() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.i_3_ = 0;
  _impl_._has_bits_[0] &= ~0x00002000u;
}
inline double PowerStateStamped::i_3() const {
  // @@protoc_insertion_point(field_get:power_msg.PowerStateStamped.i_3)
  return _internal_i_3();
}
inline void PowerStateStamped::set_i_3(double value) {
  _internal_set_i_3(value);
  _impl_._has_bits_[0] |= 0x00002000u;
  // @@protoc_insertion_point(field_set:power_msg.PowerStateStamped.i_3)
}
inline double PowerStateStamped::_internal_i_3() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.i_3_;
}
inline void PowerStateStamped::_internal_set_i_3(double value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.i_3_ = value;
}

// double v_4 = 15;
inline void PowerStateStamped::clear_v_4() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.v_4_ = 0;
  _impl_._has_bits_[0] &= ~0x00004000u;
}
inline double PowerStateStamped::v_4() const {
  // @@protoc_insertion_point(field_get:power_msg.PowerStateStamped.v_4)
  return _internal_v_4();
}
inline void PowerStateStamped::set_v_4(double value) {
  _internal_set_v_4(value);
  _impl_._has_bits_[0] |= 0x00004000u;
  // @@protoc_insertion_point(field_set:power_msg.PowerStateStamped.v_4)
}
inline double PowerStateStamped::_internal_v_4() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.v_4_;
}
inline void PowerStateStamped::_internal_set_v_4(double value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.v_4_ = value;
}

// double i_4 = 16;
inline void PowerStateStamped::clear_i_4() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.i_4_ = 0;
  _impl_._has_bits_[0] &= ~0x00008000u;
}
inline double PowerStateStamped::i_4() const {
  // @@protoc_insertion_point(field_get:power_msg.PowerStateStamped.i_4)
  return _internal_i_4();
}
inline void PowerStateStamped::set_i_4(double value) {
  _internal_set_i_4(value);
  _impl_._has_bits_[0] |= 0x00008000u;
  // @@protoc_insertion_point(field_set:power_msg.PowerStateStamped.i_4)
}
inline double PowerStateStamped::_internal_i_4() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.i_4_;
}
inline void PowerStateStamped::_internal_set_i_4(double value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.i_4_ = value;
}

// double v_5 = 17;
inline void PowerStateStamped::clear_v_5() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.v_5_ = 0;
  _impl_._has_bits_[0] &= ~0x00010000u;
}
inline double PowerStateStamped::v_5() const {
  // @@protoc_insertion_point(field_get:power_msg.PowerStateStamped.v_5)
  return _internal_v_5();
}
inline void PowerStateStamped::set_v_5(double value) {
  _internal_set_v_5(value);
  _impl_._has_bits_[0] |= 0x00010000u;
  // @@protoc_insertion_point(field_set:power_msg.PowerStateStamped.v_5)
}
inline double PowerStateStamped::_internal_v_5() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.v_5_;
}
inline void PowerStateStamped::_internal_set_v_5(double value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.v_5_ = value;
}

// double i_5 = 18;
inline void PowerStateStamped::clear_i_5() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.i_5_ = 0;
  _impl_._has_bits_[0] &= ~0x00020000u;
}
inline double PowerStateStamped::i_5() const {
  // @@protoc_insertion_point(field_get:power_msg.PowerStateStamped.i_5)
  return _internal_i_5();
}
inline void PowerStateStamped::set_i_5(double value) {
  _internal_set_i_5(value);
  _impl_._has_bits_[0] |= 0x00020000u;
  // @@protoc_insertion_point(field_set:power_msg.PowerStateStamped.i_5)
}
inline double PowerStateStamped::_internal_i_5() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.i_5_;
}
inline void PowerStateStamped::_internal_set_i_5(double value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.i_5_ = value;
}

// double v_6 = 19;
inline void PowerStateStamped::clear_v_6() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.v_6_ = 0;
  _impl_._has_bits_[0] &= ~0x00040000u;
}
inline double PowerStateStamped::v_6() const {
  // @@protoc_insertion_point(field_get:power_msg.PowerStateStamped.v_6)
  return _internal_v_6();
}
inline void PowerStateStamped::set_v_6(double value) {
  _internal_set_v_6(value);
  _impl_._has_bits_[0] |= 0x00040000u;
  // @@protoc_insertion_point(field_set:power_msg.PowerStateStamped.v_6)
}
inline double PowerStateStamped::_internal_v_6() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.v_6_;
}
inline void PowerStateStamped::_internal_set_v_6(double value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.v_6_ = value;
}

// double i_6 = 20;
inline void PowerStateStamped::clear_i_6() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.i_6_ = 0;
  _impl_._has_bits_[0] &= ~0x00080000u;
}
inline double PowerStateStamped::i_6() const {
  // @@protoc_insertion_point(field_get:power_msg.PowerStateStamped.i_6)
  return _internal_i_6();
}
inline void PowerStateStamped::set_i_6(double value) {
  _internal_set_i_6(value);
  _impl_._has_bits_[0] |= 0x00080000u;
  // @@protoc_insertion_point(field_set:power_msg.PowerStateStamped.i_6)
}
inline double PowerStateStamped::_internal_i_6() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.i_6_;
}
inline void PowerStateStamped::_internal_set_i_6(double value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.i_6_ = value;
}

#ifdef __GNUC__
#pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)
}  // namespace power_msg


namespace google {
namespace protobuf {

template <>
struct is_proto_enum<::power_msg::ROBOTMODE> : std::true_type {};
template <>
inline const EnumDescriptor* PROTOBUF_NONNULL GetEnumDescriptor<::power_msg::ROBOTMODE>() {
  return ::power_msg::ROBOTMODE_descriptor();
}

}  // namespace protobuf
}  // namespace google

// @@protoc_insertion_point(global_scope)

#include "google/protobuf/port_undef.inc"

#endif  // Power_2eproto_2epb_2eh
