// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: serviceserving.proto
#ifndef GRPC_serviceserving_2eproto__INCLUDED
#define GRPC_serviceserving_2eproto__INCLUDED

#include "serviceserving.pb.h"

#include <functional>
#include <grpcpp/generic/async_generic_service.h>
#include <grpcpp/support/async_stream.h>
#include <grpcpp/support/async_unary_call.h>
#include <grpcpp/support/client_callback.h>
#include <grpcpp/client_context.h>
#include <grpcpp/completion_queue.h>
#include <grpcpp/support/message_allocator.h>
#include <grpcpp/support/method_handler.h>
#include <grpcpp/impl/proto_utils.h>
#include <grpcpp/impl/rpc_method.h>
#include <grpcpp/support/server_callback.h>
#include <grpcpp/impl/server_callback_handlers.h>
#include <grpcpp/server_context.h>
#include <grpcpp/impl/service_type.h>
#include <grpcpp/support/status.h>
#include <grpcpp/support/stub_options.h>
#include <grpcpp/support/sync_stream.h>
#include <grpcpp/ports_def.inc>

namespace core {

class ServerClient final {
 public:
  static constexpr char const* service_full_name() {
    return "core.ServerClient";
  }
  class StubInterface {
   public:
    virtual ~StubInterface() {}
    virtual ::grpc::Status Serving(::grpc::ClientContext* context, const ::core::ServingRequest& request, ::core::ServingReply* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::core::ServingReply>> AsyncServing(::grpc::ClientContext* context, const ::core::ServingRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::core::ServingReply>>(AsyncServingRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::core::ServingReply>> PrepareAsyncServing(::grpc::ClientContext* context, const ::core::ServingRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::core::ServingReply>>(PrepareAsyncServingRaw(context, request, cq));
    }
    class async_interface {
     public:
      virtual ~async_interface() {}
      virtual void Serving(::grpc::ClientContext* context, const ::core::ServingRequest* request, ::core::ServingReply* response, std::function<void(::grpc::Status)>) = 0;
      virtual void Serving(::grpc::ClientContext* context, const ::core::ServingRequest* request, ::core::ServingReply* response, ::grpc::ClientUnaryReactor* reactor) = 0;
    };
    typedef class async_interface experimental_async_interface;
    virtual class async_interface* async() { return nullptr; }
    class async_interface* experimental_async() { return async(); }
   private:
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::core::ServingReply>* AsyncServingRaw(::grpc::ClientContext* context, const ::core::ServingRequest& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::core::ServingReply>* PrepareAsyncServingRaw(::grpc::ClientContext* context, const ::core::ServingRequest& request, ::grpc::CompletionQueue* cq) = 0;
  };
  class Stub final : public StubInterface {
   public:
    Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());
    ::grpc::Status Serving(::grpc::ClientContext* context, const ::core::ServingRequest& request, ::core::ServingReply* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::core::ServingReply>> AsyncServing(::grpc::ClientContext* context, const ::core::ServingRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::core::ServingReply>>(AsyncServingRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::core::ServingReply>> PrepareAsyncServing(::grpc::ClientContext* context, const ::core::ServingRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::core::ServingReply>>(PrepareAsyncServingRaw(context, request, cq));
    }
    class async final :
      public StubInterface::async_interface {
     public:
      void Serving(::grpc::ClientContext* context, const ::core::ServingRequest* request, ::core::ServingReply* response, std::function<void(::grpc::Status)>) override;
      void Serving(::grpc::ClientContext* context, const ::core::ServingRequest* request, ::core::ServingReply* response, ::grpc::ClientUnaryReactor* reactor) override;
     private:
      friend class Stub;
      explicit async(Stub* stub): stub_(stub) { }
      Stub* stub() { return stub_; }
      Stub* stub_;
    };
    class async* async() override { return &async_stub_; }

   private:
    std::shared_ptr< ::grpc::ChannelInterface> channel_;
    class async async_stub_{this};
    ::grpc::ClientAsyncResponseReader< ::core::ServingReply>* AsyncServingRaw(::grpc::ClientContext* context, const ::core::ServingRequest& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::core::ServingReply>* PrepareAsyncServingRaw(::grpc::ClientContext* context, const ::core::ServingRequest& request, ::grpc::CompletionQueue* cq) override;
    const ::grpc::internal::RpcMethod rpcmethod_Serving_;
  };
  static std::unique_ptr<Stub> NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());

  class Service : public ::grpc::Service {
   public:
    Service();
    virtual ~Service();
    virtual ::grpc::Status Serving(::grpc::ServerContext* context, const ::core::ServingRequest* request, ::core::ServingReply* response);
  };
  template <class BaseClass>
  class WithAsyncMethod_Serving : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_Serving() {
      ::grpc::Service::MarkMethodAsync(0);
    }
    ~WithAsyncMethod_Serving() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status Serving(::grpc::ServerContext* /*context*/, const ::core::ServingRequest* /*request*/, ::core::ServingReply* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestServing(::grpc::ServerContext* context, ::core::ServingRequest* request, ::grpc::ServerAsyncResponseWriter< ::core::ServingReply>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  typedef WithAsyncMethod_Serving<Service > AsyncService;
  template <class BaseClass>
  class WithCallbackMethod_Serving : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithCallbackMethod_Serving() {
      ::grpc::Service::MarkMethodCallback(0,
          new ::grpc::internal::CallbackUnaryHandler< ::core::ServingRequest, ::core::ServingReply>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::core::ServingRequest* request, ::core::ServingReply* response) { return this->Serving(context, request, response); }));}
    void SetMessageAllocatorFor_Serving(
        ::grpc::MessageAllocator< ::core::ServingRequest, ::core::ServingReply>* allocator) {
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::GetHandler(0);
      static_cast<::grpc::internal::CallbackUnaryHandler< ::core::ServingRequest, ::core::ServingReply>*>(handler)
              ->SetMessageAllocator(allocator);
    }
    ~WithCallbackMethod_Serving() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status Serving(::grpc::ServerContext* /*context*/, const ::core::ServingRequest* /*request*/, ::core::ServingReply* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* Serving(
      ::grpc::CallbackServerContext* /*context*/, const ::core::ServingRequest* /*request*/, ::core::ServingReply* /*response*/)  { return nullptr; }
  };
  typedef WithCallbackMethod_Serving<Service > CallbackService;
  typedef CallbackService ExperimentalCallbackService;
  template <class BaseClass>
  class WithGenericMethod_Serving : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_Serving() {
      ::grpc::Service::MarkMethodGeneric(0);
    }
    ~WithGenericMethod_Serving() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status Serving(::grpc::ServerContext* /*context*/, const ::core::ServingRequest* /*request*/, ::core::ServingReply* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithRawMethod_Serving : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_Serving() {
      ::grpc::Service::MarkMethodRaw(0);
    }
    ~WithRawMethod_Serving() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status Serving(::grpc::ServerContext* /*context*/, const ::core::ServingRequest* /*request*/, ::core::ServingReply* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestServing(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncResponseWriter< ::grpc::ByteBuffer>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithRawCallbackMethod_Serving : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawCallbackMethod_Serving() {
      ::grpc::Service::MarkMethodRawCallback(0,
          new ::grpc::internal::CallbackUnaryHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::grpc::ByteBuffer* request, ::grpc::ByteBuffer* response) { return this->Serving(context, request, response); }));
    }
    ~WithRawCallbackMethod_Serving() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status Serving(::grpc::ServerContext* /*context*/, const ::core::ServingRequest* /*request*/, ::core::ServingReply* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* Serving(
      ::grpc::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_Serving : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithStreamedUnaryMethod_Serving() {
      ::grpc::Service::MarkMethodStreamed(0,
        new ::grpc::internal::StreamedUnaryHandler<
          ::core::ServingRequest, ::core::ServingReply>(
            [this](::grpc::ServerContext* context,
                   ::grpc::ServerUnaryStreamer<
                     ::core::ServingRequest, ::core::ServingReply>* streamer) {
                       return this->StreamedServing(context,
                         streamer);
                  }));
    }
    ~WithStreamedUnaryMethod_Serving() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status Serving(::grpc::ServerContext* /*context*/, const ::core::ServingRequest* /*request*/, ::core::ServingReply* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status StreamedServing(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::core::ServingRequest,::core::ServingReply>* server_unary_streamer) = 0;
  };
  typedef WithStreamedUnaryMethod_Serving<Service > StreamedUnaryService;
  typedef Service SplitStreamedService;
  typedef WithStreamedUnaryMethod_Serving<Service > StreamedService;
};

}  // namespace core


#include <grpcpp/ports_undef.inc>
#endif  // GRPC_serviceserving_2eproto__INCLUDED
